version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_POST_API: ${REACT_APP_POST_API}
        REACT_APP_COMMENT_API: ${REACT_APP_COMMENT_API}
    ports:
      - "3000:3000"
    depends_on:
      - post-service
      - comment-service

  post-service:
    build:
      context: ./post-service
    ports:
      - "5001:5001"
    env_file:
      - ./post-service/.env

  comment-service:
    build:
      context: ./comment-service
    ports:
      - "5002:5002"
    env_file:
      - ./comment-service/.env
